Operations=["+","-","×","÷"]        #Operations for training. Only "+","-","×","÷" are accepted, you can remove them if you dont want to use
Right_answer_sound_path="Path to sounds of right answers"       # Path for sounds of correct answers.
Wrong_answer_sound_path="Path to soudns of wrong answers"        # Path for sounds of Wrong answers.
Range_addition1=[0,20]      #Range for First Number of addition
Range_addition2=[0,15]       #Range for Second Number of addition
Range_subtraction1=[0,100]       #Range for First Number of Subtraction
Range_subtraction2=[0,10]       #Range for Second Number of Subtraction
Range_multiplication =[0,10]        #Range for First Number of Multipication
Range_multiplication0 =[0,100]      #Range for Second Number of Multipication by 0
Range_multiplication1 =[0,100]
Range_multiplication2 =[0,15]
Range_multiplication3 =[0,5]
Range_multiplication4 =[0,5]
Range_multiplication5 =[0,10]
Range_multiplication6 =[0,3]
Range_multiplication7 =[0,2]
Range_multiplication8 =[0,2]
Range_multiplication9 =[0,2]
Range_multiplication10 =[0,100]
Range_devidor =[1,10]       #Range for devidor
Range_devision_result1 =[0,100]         #Range for result when devided by 1.
Range_devision_result2 =[0,15]
Range_devision_result3 =[0,4]
Range_devision_result4 =[0,3]
Range_devision_result5 =[0,10]
Range_devision_result6 =[0,2]
Range_devision_result7 =[0,2]
Range_devision_result8 =[0,2]
Range_devision_result9 =[0,2]
Range_devision_result10 =[0,10]
